# Generated by Django 2.2.7 on 2019-11-13 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191111_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full', models.CharField(max_length=32, verbose_name='Giorno e ora')),
                ('abbrev', models.CharField(max_length=4, verbose_name='Abbreviazione')),
            ],
            options={
                'verbose_name': 'Orario',
                'verbose_name_plural': 'Orari',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.CharField(blank=True, help_text='Via/Piazza, civico, CAP, Città', max_length=100, null=True, verbose_name='Indirizzo'),
        ),
        migrations.AddField(
            model_name='member',
            name='course_alt',
            field=models.CharField(blank=True, help_text="Se si è selezionato 'Altro'", max_length=100, null=True, verbose_name='Testo'),
        ),
        migrations.AddField(
            model_name='member',
            name='course_membership',
            field=models.CharField(choices=[('INTU', 'Integrazione per materiale socio UISP'), ('INTF', 'Integrazione per materiale socio FIDAL')], default='INTF', help_text='Compilare se si segue un corso', max_length=4, verbose_name='Federazione / Ente sportivo'),
        ),
        migrations.AddField(
            model_name='member',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Data di nascita'),
        ),
        migrations.AddField(
            model_name='member',
            name='email_2',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Seconda email'),
        ),
        migrations.AddField(
            model_name='member',
            name='fiscal_code',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Codice fiscale'),
        ),
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('F', 'Femmina'), ('M', 'Maschio')], default='M', max_length=1, null=True, verbose_name='Sesso'),
        ),
        migrations.AddField(
            model_name='member',
            name='mc_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Scadenza CM/CMA'),
        ),
        migrations.AddField(
            model_name='member',
            name='mc_state',
            field=models.CharField(choices=[('0-NF', 'Manca il file'), ('1-VF', 'Verifica file'), ('2-RE', 'Regolare'), ('3-SV', 'Scaduto, da verificare'), ('4-SI', 'Scaduto, inviare notifica'), ('5-NI', 'Scaduto, notifica inviata')], default='0-NF', max_length=4, verbose_name='Stato del CM/CMA'),
        ),
        migrations.AddField(
            model_name='member',
            name='med_cert',
            field=models.FileField(blank=True, null=True, upload_to=users.models.user_directory_path, verbose_name='Certificato medico'),
        ),
        migrations.AddField(
            model_name='member',
            name='membership',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tessera'),
        ),
        migrations.AddField(
            model_name='member',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nazionalità'),
        ),
        migrations.AddField(
            model_name='member',
            name='no_course_membership',
            field=models.CharField(choices=[('UNA', 'UISP non agonistico'), ('UA', 'UISP agonistico'), ('FID', 'FIDAL agonistico')], default='FID', help_text='Compilare se NON si segue un corso', max_length=4, verbose_name='Federazione / Ente sportivo'),
        ),
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefono/i'),
        ),
        migrations.AddField(
            model_name='member',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Luogo di nascita'),
        ),
        migrations.AddField(
            model_name='member',
            name='privacy',
            field=models.FileField(blank=True, null=True, upload_to=users.models.user_directory_path, verbose_name='Privacy'),
        ),
        migrations.AddField(
            model_name='member',
            name='settled',
            field=models.CharField(blank=True, choices=[('YES', 'A posto'), ('NO', 'No!')], max_length=4, null=True, verbose_name='In regola?'),
        ),
        migrations.AddField(
            model_name='member',
            name='sign_up',
            field=models.FileField(blank=True, null=True, upload_to=users.models.user_directory_path, verbose_name='Richiesta di tesseramento'),
        ),
        migrations.AlterField(
            model_name='member',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_parent', to=settings.AUTH_USER_MODEL, verbose_name='Genitore'),
        ),
        migrations.AlterField(
            model_name='member',
            name='sector',
            field=models.CharField(choices=[('0-NO', 'No'), ('1-YC', 'Sì, con il corso'), ('2-NC', 'Sì, senza corso')], default='0-NO', max_length=4, verbose_name='Corre con noi?'),
        ),
        migrations.AddField(
            model_name='member',
            name='course',
            field=models.ManyToManyField(blank=True, to='users.CourseSchedule', verbose_name='Orari scelti'),
        ),
    ]
