# Generated by Django 2.2.7 on 2019-11-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_memberpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='total_amount',
            field=models.FloatField(default=0.0, verbose_name='Importo totale'),
        ),
        migrations.AlterField(
            model_name='member',
            name='course_alt',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Altro orario'),
        ),
        migrations.AlterField(
            model_name='member',
            name='course_membership',
            field=models.CharField(blank=True, choices=[('INTU', 'Integrazione per materiale socio UISP'), ('INTF', 'Integrazione per materiale socio FIDAL')], help_text='Solo se si segue un corso', max_length=4, null=True, verbose_name='Federazione / Ente sportivo'),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Femmina'), ('M', 'Maschio')], max_length=1, null=True, verbose_name='Sesso'),
        ),
        migrations.AlterField(
            model_name='member',
            name='mc_state',
            field=models.CharField(choices=[('0-NF', 'Manca il file'), ('1-VF', 'Verifica file'), ('2-RE', 'Regolare'), ('6-IS', 'In scadenza'), ('3-SV', 'Scaduto, da verificare'), ('4-SI', 'Scaduto, inviare notifica'), ('5-NI', 'Scaduto, notifica inviata')], default='0-NF', max_length=4, verbose_name='Stato del CM/CMA'),
        ),
        migrations.AlterField(
            model_name='member',
            name='no_course_membership',
            field=models.CharField(blank=True, choices=[('UNA', 'UISP non agonistico'), ('UA', 'UISP agonistico'), ('FID', 'FIDAL agonistico')], help_text='Solo se non si segue un corso', max_length=4, null=True, verbose_name='Federazione / Ente sportivo'),
        ),
        migrations.AlterField(
            model_name='member',
            name='settled',
            field=models.CharField(blank=True, choices=[('VI', 'Verifica importo totale'), ('YES', 'A posto'), ('NO', 'No!')], max_length=4, null=True, verbose_name='In regola?'),
        ),
    ]
