# Generated by Django 2.2.7 on 2019-11-17 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191116_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=50, verbose_name='Cognome')),
                ('email', models.EmailField(max_length=254, verbose_name='Indirizzo email')),
                ('sector', models.CharField(choices=[('0-NO', 'No'), ('1-YC', 'Sì, con il corso'), ('2-NC', 'Sì, senza corso')], default='0-NO', max_length=4, verbose_name='Vuoi correre con noi?')),
                ('privacy', models.BooleanField(default=False, editable=False, verbose_name="Letto l'informativa sulla privacy?")),
            ],
            options={
                'verbose_name': 'Richiedente',
                'verbose_name_plural': 'Richiedenti',
            },
        ),
        migrations.CreateModel(
            name='ApplicantChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=50, verbose_name='Cognome')),
                ('parent', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='applicant_children', to='users.Applicant')),
            ],
        ),
    ]
