# Generated by Django 2.2.7 on 2019-11-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_applicant_applicantchild'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicantchild',
            options={'verbose_name': 'Figlio', 'verbose_name_plural': 'Figli'},
        ),
        migrations.AddField(
            model_name='applicant',
            name='children_str',
            field=models.TextField(blank=True, help_text='Nome e cognome dei figli che si intende iscrivere, separati da una virgola.', max_length=200, null=True, verbose_name='Figli'),
        ),
    ]
