# Generated by Django 2.2.7 on 2019-11-19 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20191119_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='privacy',
        ),
    ]
