# Generated by Django 2.2.7 on 2019-11-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20191122_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full', models.CharField(max_length=32, verbose_name='Giorno e ora')),
                ('abbrev', models.CharField(max_length=4, verbose_name='Abbreviazione')),
            ],
            options={
                'verbose_name': 'Orario',
                'verbose_name_plural': 'Orari',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='course',
            field=models.ManyToManyField(blank=True, to='users.CourseSchedule', verbose_name='Orari scelti'),
        ),
    ]
