# Generated by Django 2.2.7 on 2019-11-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagine', '0002_auto_20191122_1418'),
        ('users', '0012_auto_20191122_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='course2',
            field=models.ManyToManyField(blank=True, to='pagine.CourseSchedule2', verbose_name='Orari scelti'),
        ),
    ]
