# Generated by Django 2.2.7 on 2019-11-22 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_member_course2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='course',
        ),
        migrations.DeleteModel(
            name='CourseSchedule',
        ),
    ]
