# Generated by Django 2.2.7 on 2019-11-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_member_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='thumb',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
    ]
