# Generated by Django 2.2.7 on 2019-12-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_usermessage_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Inviato da'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='recipient',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Destinatario'),
        ),
    ]
