# Generated by Django 2.2.7 on 2019-12-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20191213_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='notice',
            field=models.CharField(blank=True, choices=[('SPAM', 'Da inviare'), ('DONE', 'Già inviata')], max_length=4, null=True, verbose_name='Notifica via email'),
        ),
    ]
