# Generated by Django 2.2.7 on 2019-12-15 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20191214_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='course2',
        ),
    ]
