# Generated by Django 2.2.7 on 2019-12-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20191215_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='no_spam',
            field=models.BooleanField(default=True, help_text='Vuoi ricevere notifiche sugli eventi?', verbose_name='Mailing list'),
        ),
    ]
