# Generated by Django 2.2.7 on 2019-12-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_member_no_spam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mc_state',
            field=models.CharField(blank=True, choices=[('0-NF', 'Manca il file'), ('1-VF', 'Verifica file'), ('2-RE', 'Regolare'), ('6-IS', 'In scadenza'), ('3-SV', 'Scaduto, da verificare'), ('4-SI', 'Scaduto, inviare notifica'), ('5-NI', 'Scaduto, notifica inviata')], max_length=4, null=True, verbose_name='Stato del CM/CMA'),
        ),
    ]
