# Generated by Django 2.2.7 on 2020-01-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_member_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(default='a@b.com', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(default='Nome', max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(default='Cognome', max_length=50, verbose_name='Cognome'),
        ),
    ]
