# Generated by Django 2.2.7 on 2020-01-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20200108_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='sector',
            field=models.CharField(choices=[('0-NO', 'No'), ('3-FI', 'No, solo i figli'), ('1-YC', 'Sì, con il corso'), ('2-NC', 'Sì, senza corso')], default='0-NO', max_length=4, verbose_name='Vuoi correre con noi?'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(default='me@example.com', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='member',
            name='sector',
            field=models.CharField(choices=[('0-NO', 'No'), ('3-FI', 'No, solo i figli'), ('1-YC', 'Sì, con il corso'), ('2-NC', 'Sì, senza corso')], default='0-NO', max_length=4, verbose_name='Corre con noi?'),
        ),
    ]
