# Generated by Django 2.2.7 on 2019-12-20 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagine', '0034_auto_20191220_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Il nome della gara', max_length=50, verbose_name='Nome')),
                ('slug', models.SlugField(editable=False, null=True)),
                ('date', models.DateField(blank=True, help_text='In mancanza di Evento', null=True, verbose_name='Data')),
                ('location', models.CharField(blank=True, help_text='In mancanza di Evento', max_length=50, null=True, verbose_name='Luogo')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descrizione')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pagine.Event', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Gara',
                'verbose_name_plural': 'Gare',
                'ordering': ('-id',),
            },
        ),
    ]
