# Generated by Django 2.2.7 on 2019-12-20 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('criterium', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='type',
            field=models.CharField(blank=True, choices=[('P', 'Pista'), ('M', 'Maratona'), ('H', 'Mezza maratona'), ('C', 'Cross'), ('10', '10 mila')], max_length=4, null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='race',
            name='location',
            field=models.ForeignKey(blank=True, help_text='In mancanza di Evento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pagine.Location', verbose_name='Luogo'),
        ),
    ]
