# Generated by Django 2.2.7 on 2019-12-20 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('criterium', '0002_auto_20191220_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(verbose_name='Punti')),
                ('placement', models.IntegerField(blank=True, null=True, verbose_name='Piazzamento')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Tempo')),
                ('race', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='criterium.Race')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Iscritto')),
            ],
            options={
                'verbose_name': 'Atleta',
                'verbose_name_plural': 'Atleti/e',
                'ordering': ('-id',),
            },
        ),
    ]
