# Generated by Django 2.2.7 on 2019-12-21 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('criterium', '0003_athlete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='placement',
            field=models.IntegerField(blank=True, null=True, verbose_name='Piazzamento assoluto'),
        ),
        migrations.AlterField(
            model_name='race',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_race', to='pagine.Event', verbose_name='Evento'),
        ),
    ]
