# Generated by Django 2.2.7 on 2019-12-27 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criterium', '0004_auto_20191221_1043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='race',
            options={'ordering': ('-date',), 'verbose_name': 'Gara', 'verbose_name_plural': 'Gare'},
        ),
    ]
