# Generated by Django 2.2.7 on 2020-01-09 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20200109_2155'),
        ('criterium', '0005_auto_20191227_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='user',
        ),
        migrations.AddField(
            model_name='athlete',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Member', verbose_name='Iscritto'),
        ),
    ]
