# Generated by Django 3.0.2 on 2020-03-03 20:58

from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('streamblocks', '0008_eventupgrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_image', filebrowser.fields.FileBrowseField(max_length=200, null=True, verbose_name='Immagine')),
                ('caption', models.CharField(blank=True, max_length=200, null=True, verbose_name='Didascalia')),
            ],
            options={
                'verbose_name': 'Galleria di immagini',
                'verbose_name_plural': 'Gallerie di immagini',
            },
        ),
    ]
