# Generated by Django 3.0.2 on 2020-03-06 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamblocks', '0011_landscapegallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landscapegallery',
            options={'verbose_name': 'Galleria di immagini orizzontali', 'verbose_name_plural': 'Galleria di immagini orizzontali'},
        ),
    ]
