# Generated by Django 3.0.2 on 2020-03-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamblocks', '0012_auto_20200306_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexedparagraph',
            name='parent_id',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='indexedparagraph',
            name='parent_type',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
