# Generated by Django 2.2.7 on 2019-11-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full', models.CharField(max_length=32, verbose_name='Giorno e ora')),
                ('abbrev', models.CharField(max_length=8, verbose_name='Abbreviazione')),
            ],
            options={
                'verbose_name': 'Orario',
                'verbose_name_plural': 'Orari',
            },
        ),
    ]
