# Generated by Django 2.2.7 on 2019-11-22 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagine', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseSchedule',
            new_name='CourseSchedule2',
        ),
    ]
