# Generated by Django 2.2.7 on 2019-11-22 15:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagine', '0002_auto_20191122_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Il nome del luogo', max_length=50, verbose_name='Titolo')),
                ('address', models.TextField(max_length=200, verbose_name='Indirizzo')),
                ('gmap_link', models.URLField(help_text="Dal menu di Google Maps seleziona 'Condividi/link',                    copia il link e incollalo qui", null=True, verbose_name='Link di Google Map')),
                ('gmap_embed', models.URLField(help_text="Dal menu di Google Maps seleziona 'Condividi/incorpora',                    copia il link (pulito) e incollalo qui", max_length=500, null=True, verbose_name='Incorpora Google Map')),
                ('body', ckeditor.fields.RichTextField(max_length=50, verbose_name='Descrizione')),
            ],
            options={
                'verbose_name': 'Luogo',
                'verbose_name_plural': 'Luoghi',
            },
        ),
    ]
