# Generated by Django 2.2.7 on 2019-11-22 15:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagine', '0003_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(help_text='Via/Piazza, civico, CAP, Città', max_length=200, verbose_name='Indirizzo'),
        ),
        migrations.AlterField(
            model_name='location',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='Descrizione'),
        ),
        migrations.AlterField(
            model_name='location',
            name='gmap_embed',
            field=models.URLField(help_text="Dal menu di Google Maps seleziona 'Condividi/incorpora',                    copia il link e incollalo qui", max_length=500, null=True, verbose_name='Incorpora Google Map'),
        ),
        migrations.AlterField(
            model_name='location',
            name='title',
            field=models.CharField(help_text='Il nome del luogo', max_length=50, verbose_name='Titolo'),
        ),
    ]
