# Generated by Django 2.2.7 on 2019-11-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagine', '0005_auto_20191122_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='slug',
            field=models.SlugField(default='casa-di-marco', unique=True),
            preserve_default=False,
        ),
    ]
