# Generated by Django 2.2.7 on 2019-11-22 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagine', '0006_location_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='gmap_embed',
            field=models.TextField(blank=True, help_text="Dal menu di Google Maps seleziona 'Condividi/incorpora',                    copia il link e incollalo qui", max_length=500, null=True, verbose_name='Incorpora Google Map'),
        ),
    ]
