# Generated by Django 2.2.7 on 2019-11-24 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20191122_1433'),
        ('pagine', '0007_auto_20191123_0027'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseSchedule2',
            new_name='CourseSchedule',
        ),
    ]
