# Generated by Django 2.2.7 on 2019-11-24 18:17

from django.db import migrations, models
import pagine.models


class Migration(migrations.Migration):

    dependencies = [
        ('pagine', '0008_auto_20191124_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('image', models.ImageField(upload_to=pagine.models.date_directory_path)),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrizione')),
            ],
            options={
                'verbose_name': 'Immagine',
                'verbose_name_plural': 'Immagini',
            },
        ),
    ]
