# Generated by Django 2.2.7 on 2019-11-24 18:52

from django.db import migrations, models
import pagine.models


class Migration(migrations.Migration):

    dependencies = [
        ('pagine', '0009_imageentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageentry',
            name='thumb',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=pagine.models.date_directory_path),
        ),
    ]
