# Generated by Django 2.2.7 on 2019-11-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagine', '0010_imageentry_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageentry',
            name='thumb',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
    ]
