# Generated by Django 2.2.7 on 2019-11-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagine', '0011_auto_20191124_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageentry',
            name='thumb',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
    ]
