# Generated by Django 2.2.7 on 2019-11-24 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagine', '0012_auto_20191124_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pagine.ImageEntry'),
        ),
        migrations.AlterField(
            model_name='location',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione'),
        ),
    ]
