# Generated by Django 2.2.7 on 2019-11-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagine', '0013_auto_20191124_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageentry',
            name='name',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Nome'),
        ),
    ]
