# Generated by Django 2.2.7 on 2019-12-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagine', '0014_imageentry_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Immagine'),
        ),
    ]
