# Generated by Django 2.2.7 on 2019-12-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagine', '0016_auto_20191202_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
