# Generated by Django 2.2.7 on 2019-12-02 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagine', '0017_location_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='image2',
        ),
    ]
