# Generated by Django 2.2.7 on 2019-12-05 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagine', '0018_remove_location_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='location',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefono/i'),
        ),
        migrations.AddField(
            model_name='location',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Sito internet'),
        ),
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pagine.ImageEntry', verbose_name='Immagine'),
        ),
    ]
