# Generated by Django 2.2.7 on 2019-12-06 18:20

import ckeditor_uploader.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pagine', '0021_auto_20191206_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Lancio'),
        ),
        migrations.AddField(
            model_name='event',
            name='intro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Introduzione'),
        ),
        migrations.AddField(
            model_name='event',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsabile'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 6, 19, 20, 53, 338787), verbose_name='Quando'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Lista di categorie separate da virgole', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Categorie'),
        ),
        migrations.CreateModel(
            name='EventUpgrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Il titolo dell'aggiornamento", max_length=50, verbose_name='Titolo')),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 12, 6, 19, 20, 53, 338787), verbose_name='Data')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Lancio')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_upgrades', to='pagine.Event')),
            ],
            options={
                'verbose_name': 'Aggiornamento',
                'verbose_name_plural': 'Aggiornamenti',
                'ordering': ('date',),
            },
        ),
    ]
