# Generated by Django 2.2.7 on 2019-12-12 16:32

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagine', '0022_auto_20191206_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 12, 17, 32, 47, 682093), verbose_name='Quando'),
        ),
        migrations.AlterField(
            model_name='eventupgrade',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Aggiornamento'),
        ),
        migrations.AlterField(
            model_name='eventupgrade',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 12, 17, 32, 47, 682093), verbose_name='Data'),
        ),
    ]
