# Generated by Django 2.2.7 on 2019-12-13 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagine', '0023_auto_20191212_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-date',), 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventi'},
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 13, 12, 7, 55, 189618), verbose_name='Quando'),
        ),
        migrations.AlterField(
            model_name='eventupgrade',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 13, 12, 7, 55, 189618), verbose_name='Data'),
        ),
    ]
