# Generated by Django 2.2.7 on 2019-12-13 21:32

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagine', '0024_auto_20191213_1207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventupgrade',
            options={'ordering': ('-date',), 'verbose_name': 'Aggiornamento', 'verbose_name_plural': 'Aggiornamenti'},
        ),
        migrations.AlterField(
            model_name='event',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(default="Inserisci qui i dati dell'evento", verbose_name='Lancio'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 13, 22, 32, 30, 198258), verbose_name='Quando'),
        ),
        migrations.AlterField(
            model_name='event',
            name='intro',
            field=models.CharField(default='Un altro appuntamento con RP!', max_length=100, verbose_name='Introduzione'),
        ),
        migrations.AlterField(
            model_name='eventupgrade',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(default="Inserisci qui i dati dell'aggiornamento", verbose_name='Aggiornamento'),
        ),
        migrations.AlterField(
            model_name='eventupgrade',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 13, 22, 32, 30, 198258), verbose_name='Data'),
        ),
    ]
