# Generated by Django 2.2.7 on 2019-12-15 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_remove_member_course2'),
        ('pagine', '0027_auto_20191214_1158'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseSchedule',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 15, 16, 4, 26, 140023), verbose_name='Quando'),
        ),
        migrations.AlterField(
            model_name='eventupgrade',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 15, 16, 4, 26, 140023), verbose_name='Data'),
        ),
    ]
