# Generated by Django 2.2.7 on 2019-12-15 23:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pagine.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pagine', '0029_auto_20191215_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 16, 0, 19, 23, 948973), verbose_name='Quando'),
        ),
        migrations.AlterField(
            model_name='eventupgrade',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 16, 0, 19, 23, 964594), verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='eventupgrade',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_upgrades', to='pagine.Event'),
        ),
        migrations.CreateModel(
            name='UserUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 12, 16, 0, 19, 23, 964594))),
                ('image', models.ImageField(blank=True, null=True, upload_to=pagine.models.date_directory_path, verbose_name='Immagine')),
                ('body', models.TextField(help_text='Scrivi qualcosa.', verbose_name='Testo')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_uploads', to='pagine.Event')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contributo',
                'verbose_name_plural': 'Contributi',
                'ordering': ('-date',),
            },
        ),
    ]
