# Generated by Django 2.2.7 on 2019-12-16 16:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagine', '0030_auto_20191216_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 16, 17, 3, 28, 709027), verbose_name='Quando'),
        ),
        migrations.AlterField(
            model_name='eventupgrade',
            name='body',
            field=models.TextField(default="Inserisci qui i dati dell'aggiornamento", verbose_name='Aggiornamento'),
        ),
        migrations.AlterField(
            model_name='eventupgrade',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 16, 17, 3, 28, 709027), verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='userupload',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 16, 17, 3, 28, 709027), verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='userupload',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utente'),
        ),
    ]
