# Generated by Django 2.2.7 on 2019-12-18 22:50

import ckeditor_uploader.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('pagine', '0031_auto_20191216_1703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userupload',
            options={'ordering': ('-id',), 'verbose_name': 'Contributo', 'verbose_name_plural': 'Contributi'},
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 18, 23, 50, 7, 239169), verbose_name='Quando'),
        ),
        migrations.AlterField(
            model_name='eventupgrade',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 18, 23, 50, 7, 239169), verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='userupload',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 18, 23, 50, 7, 239169), verbose_name='Data'),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Il titolo dell'articolo", max_length=50, verbose_name='Titolo')),
                ('slug', models.SlugField(editable=False, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 12, 18, 23, 50, 7, 239169), verbose_name='Data')),
                ('intro', models.CharField(default='Un altro articolo di approfondimento da RP!', max_length=100, verbose_name='Introduzione')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(default="Inserisci qui il testo dell'articolo", verbose_name='Testo')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autore')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pagine.ImageEntry', verbose_name='Immagine')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='Lista di categorie separate da virgole', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Categorie')),
            ],
            options={
                'verbose_name': 'Articolo',
                'verbose_name_plural': 'Articoli',
                'ordering': ('-date',),
            },
        ),
    ]
