# Generated by Django 2.2.7 on 2019-12-19 12:43

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagine', '0032_auto_20191218_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='userupload',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_uploads', to='pagine.Blog'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Scrivi qualcosa.', verbose_name='Testo'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 19, 13, 43, 17, 904835), verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='event',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Scrivi qualcosa.', verbose_name='Lancio'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 19, 13, 43, 17, 904835), verbose_name='Quando'),
        ),
        migrations.AlterField(
            model_name='eventupgrade',
            name='body',
            field=models.TextField(help_text='Scrivi qualcosa.', verbose_name='Aggiornamento'),
        ),
        migrations.AlterField(
            model_name='eventupgrade',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 19, 13, 43, 17, 904835), verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='userupload',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 19, 13, 43, 17, 904835), verbose_name='Data'),
        ),
    ]
