# Generated by Django 2.2.7 on 2019-12-27 11:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pagine', '0039_auto_20191227_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 27, 11, 37, 27, 619965, tzinfo=utc), verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 27, 11, 37, 27, 618968, tzinfo=utc), verbose_name='Quando'),
        ),
        migrations.AlterField(
            model_name='eventupgrade',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 27, 11, 37, 27, 619965, tzinfo=utc), verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='userupload',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 27, 11, 37, 27, 620962, tzinfo=utc), verbose_name='Data'),
        ),
    ]
