# Generated by Django 2.2.7 on 2019-12-31 15:53

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pagine', '0040_auto_20191227_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='restricted',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Inserisci qui materiale riservato ai soci', null=True, verbose_name='Area riservata'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 31, 15, 53, 28, 401151, tzinfo=utc), verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 31, 15, 53, 28, 401151, tzinfo=utc), verbose_name='Quando'),
        ),
        migrations.AlterField(
            model_name='event',
            name='notice',
            field=models.CharField(blank=True, choices=[('SPAM', 'Da inviare'), ('DONE', 'Già inviata')], help_text="Se devi inviare un aggiornamento, prima salvi, poi\n            imposti su 'Da Inviare' e poi salvi di nuovo. Funzione da migliorare\n            ", max_length=4, null=True, verbose_name='Notifica via email'),
        ),
        migrations.AlterField(
            model_name='eventupgrade',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 31, 15, 53, 28, 401151, tzinfo=utc), verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='userupload',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 31, 15, 53, 28, 416772, tzinfo=utc), verbose_name='Data'),
        ),
    ]
