# Generated by Django 2.2.7 on 2020-01-02 14:38

import direzione.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagine', '0044_auto_20200101_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Il nome della convenzione', max_length=50, verbose_name='Nome')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descrizione')),
                ('location', models.ForeignKey(blank=True, help_text='Inserire indirizzo e contatti', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pagine.Location', verbose_name='Indirizzo')),
            ],
            options={
                'verbose_name': 'Convenzione',
                'verbose_name_plural': 'Convenzioni',
            },
        ),
        migrations.CreateModel(
            name='ConventionUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Il nome file', max_length=50, verbose_name='Nome')),
                ('upload', models.FileField(help_text='File da caricare', upload_to=direzione.models.user_directory_path, verbose_name='File')),
                ('convention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convention_upload', to='direzione.Convention')),
            ],
        ),
    ]
