# Generated by Django 3.0.2 on 2020-01-25 22:13

import ckeditor_uploader.fields
import direzione.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('direzione', '0001_initial'), ('direzione', '0002_auto_20200102_1711'), ('direzione', '0003_society'), ('direzione', '0004_auto_20200107_1110'), ('direzione', '0005_auto_20200107_1734'), ('direzione', '0006_auto_20200107_1739'), ('direzione', '0007_auto_20200107_1849'), ('direzione', '0008_institutional'), ('direzione', '0009_institutional_type'), ('direzione', '0010_auto_20200125_0842'), ('direzione', '0011_paragraph_title'), ('direzione', '0012_auto_20200125_0852')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pagine', '0044_auto_20200101_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Il nome della convenzione', max_length=50, verbose_name='Nome')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descrizione')),
                ('location', models.ForeignKey(blank=True, help_text='Inserire indirizzo e contatti', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pagine.Location', verbose_name='Indirizzo')),
                ('slug', models.SlugField(editable=False, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Convenzione',
                'verbose_name_plural': 'Convenzioni',
            },
        ),
        migrations.CreateModel(
            name='ConventionUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Il nome file', max_length=50, verbose_name='Nome')),
                ('upload', models.FileField(help_text='File da caricare', upload_to=direzione.models.user_directory_path, verbose_name='File')),
                ('convention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convention_upload', to='direzione.Convention')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Il nome della società', max_length=50, verbose_name='Nome')),
                ('denomination', models.CharField(choices=[('ASD', 'Associazione Sportiva Dilettantistica'), ('SSD', 'Società Sportiva Dilettantistica')], max_length=4, verbose_name='Denominazione')),
                ('coni', models.CharField(blank=True, max_length=10, null=True, verbose_name='Registro CONI')),
                ('fidal', models.CharField(blank=True, max_length=10, null=True, verbose_name='Affiliazione FIDAL')),
                ('fiscal_code', models.CharField(blank=True, max_length=11, null=True, verbose_name='Codice Fiscale')),
                ('iban', models.CharField(blank=True, max_length=27, null=True, verbose_name='Codice IBAN')),
                ('executive', models.ManyToManyField(related_name='society_executive', to='users.Member', verbose_name='Dirigenti')),
                ('president', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='society_president', to='users.Member', verbose_name='Presidente')),
                ('trainers', models.ManyToManyField(related_name='society_trainers', to='users.Member', verbose_name='Istruttori')),
                ('location', models.ForeignKey(help_text='Inserisce indirizzo e contatti', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pagine.Location', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Dati societari',
                'verbose_name_plural': 'Dati societari',
            },
        ),
        migrations.CreateModel(
            name='Institutional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Titolo')),
                ('intro', models.TextField(blank=True, max_length=200, null=True, verbose_name='Introduzione')),
                ('type', models.CharField(choices=[('1-IS', 'Iscrizioni'), ('2-ST', 'Storia'), ('3-PR', 'Privacy')], max_length=4, null=True, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Pagina istituzionale',
                'verbose_name_plural': 'Pagine istituzionali',
            },
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text="Numero d'ordine, per ora da inserire manualmente", verbose_name='Numero')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Scrivi qualcosa.', null=True, verbose_name='Testo')),
                ('institutional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutional_paragraph', to='direzione.Institutional')),
                ('title', models.CharField(help_text='Paragrafo (corpo &lt;h4&gt;) inserito nel sommario', max_length=50, null=True, verbose_name='Titolo')),
            ],
            options={
                'verbose_name': 'Paragrafo',
                'verbose_name_plural': 'Paragrafi',
                'ordering': ('number', '-id'),
            },
        ),
    ]
