# Generated by Django 2.2.7 on 2020-01-06 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('direzione', '0002_auto_20200102_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Il nome della società', max_length=50, verbose_name='Nome')),
                ('denomination', models.CharField(choices=[('ASD', 'Associazione Sportiva Dilettantistica'), ('SSD', 'Società Sportiva Dilettantistica')], max_length=4, verbose_name='Denominazione')),
                ('coni', models.CharField(blank=True, max_length=10, null=True, verbose_name='Registro CONI')),
                ('fidal', models.CharField(blank=True, max_length=10, null=True, verbose_name='Affiliazione FIDAL')),
                ('fiscal_code', models.CharField(blank=True, max_length=11, null=True, verbose_name='Codice Fiscale')),
                ('iban', models.CharField(blank=True, max_length=27, null=True, verbose_name='Codice IBAN')),
                ('executive', models.ManyToManyField(related_name='society_executive', to=settings.AUTH_USER_MODEL, verbose_name='Dirigenti')),
                ('president', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='society_president', to=settings.AUTH_USER_MODEL, verbose_name='Presidente')),
                ('trainers', models.ManyToManyField(related_name='society_trainers', to=settings.AUTH_USER_MODEL, verbose_name='Istruttori')),
            ],
            options={
                'verbose_name': 'Dati societari',
            },
        ),
    ]
