# Generated by Django 2.2.7 on 2020-01-07 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagine', '0044_auto_20200101_1634'),
        ('direzione', '0003_society'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='society',
            options={'verbose_name': 'Dati societari', 'verbose_name_plural': 'Dati societari'},
        ),
        migrations.AddField(
            model_name='society',
            name='location',
            field=models.ForeignKey(help_text='Inserire indirizzo e contatti', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pagine.Location', verbose_name='Sede'),
        ),
    ]
