# Generated by Django 2.2.7 on 2020-01-07 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('direzione', '0004_auto_20200107_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society',
            name='executive',
            field=models.ManyToManyField(related_name='society_executive', to='users.Member', verbose_name='Dirigenti'),
        ),
        migrations.AlterField(
            model_name='society',
            name='location',
            field=models.ForeignKey(help_text='Inserisce indirizzo e contatti', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pagine.Location', verbose_name='Sede'),
        ),
        migrations.AlterField(
            model_name='society',
            name='president',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='society_president', to='users.Member', verbose_name='Presidente'),
        ),
        migrations.AlterField(
            model_name='society',
            name='trainers',
            field=models.ManyToManyField(related_name='society_trainers', to='users.Member', verbose_name='Istruttori'),
        ),
    ]
