# Generated by Django 3.0.2 on 2020-01-24 14:05

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direzione', '0007_auto_20200107_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institutional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Titolo')),
                ('intro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Introduzione')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(help_text='Scrivi qualcosa.', verbose_name='Testo')),
            ],
            options={
                'verbose_name': 'Pagina istituzionale',
                'verbose_name_plural': 'Pagine istituzionali',
            },
        ),
    ]
