# Generated by Django 3.0.2 on 2020-01-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direzione', '0008_institutional'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutional',
            name='type',
            field=models.CharField(choices=[('1-IS', 'Iscrizioni'), ('2-ST', 'Storia'), ('3-PR', 'Privacy')], max_length=4, null=True, verbose_name='Tipo'),
        ),
    ]
