# Generated by Django 3.0.2 on 2020-01-25 07:42

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('direzione', '0009_institutional_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutional',
            name='body',
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text="Numero d'ordine, per ora da inserire manualmente", verbose_name='Numero')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Scrivi qualcosa.', null=True, verbose_name='Testo')),
                ('institutional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutional_paragraph', to='direzione.Institutional')),
            ],
            options={
                'verbose_name': 'Paragrafo',
                'verbose_name_plural': 'Paragrafi',
                'ordering': ('number', '-id'),
            },
        ),
    ]
