# Generated by Django 3.0.2 on 2020-01-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direzione', '0010_auto_20200125_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='title',
            field=models.CharField(help_text='Paragrafo <h4> inserito nel sommario', max_length=50, null=True, verbose_name='Titolo'),
        ),
    ]
