# Generated by Django 3.0.2 on 2020-01-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direzione', '0011_paragraph_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutional',
            name='intro',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Introduzione'),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='title',
            field=models.CharField(help_text='Paragrafo (corpo &lt;h4&gt;) inserito nel sommario', max_length=50, null=True, verbose_name='Titolo'),
        ),
    ]
